// ============================================================
//  QuizAI — script.js  (No API Key Required)
//  Quiz questions are pre-generated by AI and bundled here.
//  To regenerate questions, use the QuizAI Builder tool.
// ============================================================

// ---- State ----
let currentQuiz = [];
let userAnswers = {};

// ============================================================
//  QUESTION BANK — AI-generated questions bundled by topic
//  Add more topics by running the builder and pasting below.
// ============================================================
const QUESTION_BANK = {
  "science": {
    easy: [
      { question: "What planet is closest to the Sun?", choices: ["Venus", "Mercury", "Mars", "Earth"], answer: 1 },
      { question: "What gas do plants absorb from the air?", choices: ["Oxygen", "Nitrogen", "Carbon Dioxide", "Hydrogen"], answer: 2 },
      { question: "How many bones are in the adult human body?", choices: ["206", "198", "215", "230"], answer: 0 },
      { question: "What is the chemical symbol for water?", choices: ["WO", "H2O", "HO2", "OW"], answer: 1 },
      { question: "What force keeps us on the ground?", choices: ["Magnetism", "Friction", "Gravity", "Inertia"], answer: 2 }
    ],
    medium: [
      { question: "What is the powerhouse of the cell?", choices: ["Nucleus", "Ribosome", "Mitochondria", "Vacuole"], answer: 2 },
      { question: "What is the speed of light in a vacuum?", choices: ["300,000 km/s", "150,000 km/s", "450,000 km/s", "200,000 km/s"], answer: 0 },
      { question: "Which element has the atomic number 1?", choices: ["Helium", "Oxygen", "Hydrogen", "Carbon"], answer: 2 },
      { question: "What type of rock is formed from cooled magma?", choices: ["Sedimentary", "Metamorphic", "Igneous", "Limestone"], answer: 2 },
      { question: "How many chromosomes do humans normally have?", choices: ["44", "46", "48", "42"], answer: 1 }
    ],
    hard: [
      { question: "What is the Schwarzschild radius?", choices: ["The radius of the Sun", "The radius at which escape velocity equals light speed", "The distance of Earth from the Sun", "The radius of a neutron star"], answer: 1 },
      { question: "Which particle carries the weak nuclear force?", choices: ["Photon", "Gluon", "W and Z bosons", "Graviton"], answer: 2 },
      { question: "What is the half-life of Carbon-14?", choices: ["1,500 years", "3,200 years", "5,730 years", "10,000 years"], answer: 2 },
      { question: "What phenomenon does the Meissner effect describe?", choices: ["Radioactive decay", "Expulsion of magnetic fields from superconductors", "Laser emission", "Quantum tunneling"], answer: 1 },
      { question: "Which law states that pressure and volume are inversely proportional at constant temperature?", choices: ["Charles's Law", "Avogadro's Law", "Boyle's Law", "Gay-Lussac's Law"], answer: 2 }
    ]
  },
  "history": {
    easy: [
      { question: "Who was the first President of the United States?", choices: ["John Adams", "Thomas Jefferson", "George Washington", "Benjamin Franklin"], answer: 2 },
      { question: "In what year did World War II end?", choices: ["1943", "1944", "1946", "1945"], answer: 3 },
      { question: "Which ancient wonder was located in Egypt?", choices: ["Hanging Gardens", "Colossus of Rhodes", "Great Pyramid of Giza", "Temple of Artemis"], answer: 2 },
      { question: "What wall separated East and West Berlin?", choices: ["Iron Curtain", "Berlin Wall", "Hadrian's Wall", "Great Wall"], answer: 1 },
      { question: "Who wrote the Declaration of Independence?", choices: ["George Washington", "John Adams", "Benjamin Franklin", "Thomas Jefferson"], answer: 3 }
    ],
    medium: [
      { question: "What empire did Genghis Khan found?", choices: ["Ottoman Empire", "Mongol Empire", "Ming Dynasty", "Roman Empire"], answer: 1 },
      { question: "In what year did the French Revolution begin?", choices: ["1776", "1799", "1789", "1804"], answer: 2 },
      { question: "Which country was the first to grant women the right to vote?", choices: ["USA", "UK", "New Zealand", "Australia"], answer: 2 },
      { question: "What ship sank on its maiden voyage in 1912?", choices: ["Olympic", "Lusitania", "Britannic", "Titanic"], answer: 3 },
      { question: "Who was the last pharaoh of Ancient Egypt?", choices: ["Nefertiti", "Cleopatra VII", "Hatshepsut", "Ramesses II"], answer: 1 }
    ],
    hard: [
      { question: "What year did the Ottoman Empire formally dissolve?", choices: ["1918", "1920", "1922", "1924"], answer: 2 },
      { question: "Which treaty ended the Thirty Years' War?", choices: ["Treaty of Utrecht", "Peace of Westphalia", "Treaty of Paris", "Congress of Vienna"], answer: 1 },
      { question: "Who led the Haitian Revolution to independence?", choices: ["Simón Bolívar", "Jean-Jacques Dessalines", "Toussaint Louverture", "Henri Christophe"], answer: 2 },
      { question: "What was the Zimmermann Telegram about?", choices: ["Peace negotiations with France", "A German proposal for Mexico to attack the USA", "A spy scandal in Britain", "Naval blockade terms"], answer: 1 },
      { question: "Which Chinese dynasty built most of the Great Wall?", choices: ["Han", "Tang", "Qin", "Ming"], answer: 3 }
    ]
  },
  "geography": {
    easy: [
      { question: "What is the largest continent?", choices: ["Africa", "North America", "Asia", "Europe"], answer: 2 },
      { question: "What is the capital of France?", choices: ["Lyon", "Marseille", "Paris", "Bordeaux"], answer: 2 },
      { question: "Which ocean is the largest?", choices: ["Atlantic", "Indian", "Arctic", "Pacific"], answer: 3 },
      { question: "How many continents are there on Earth?", choices: ["5", "6", "7", "8"], answer: 2 },
      { question: "What is the longest river in the world?", choices: ["Amazon", "Nile", "Mississippi", "Yangtze"], answer: 1 }
    ],
    medium: [
      { question: "What is the smallest country in the world?", choices: ["Monaco", "San Marino", "Vatican City", "Liechtenstein"], answer: 2 },
      { question: "Which country has the most natural lakes?", choices: ["Russia", "USA", "Brazil", "Canada"], answer: 3 },
      { question: "What is the capital of Australia?", choices: ["Sydney", "Melbourne", "Canberra", "Brisbane"], answer: 2 },
      { question: "Through how many countries does the Amazon River flow?", choices: ["2", "3", "4", "5"], answer: 1 },
      { question: "What is the highest mountain in Africa?", choices: ["Mount Kenya", "Mount Kilimanjaro", "Rwenzori", "Drakensberg"], answer: 1 }
    ],
    hard: [
      { question: "What is the Afar Triangle known for geologically?", choices: ["Volcanic hotspot", "A tectonic triple junction", "Largest desert basin", "Deepest ocean trench"], answer: 1 },
      { question: "Which country has the most time zones?", choices: ["Russia", "USA", "China", "France"], answer: 3 },
      { question: "What is the deepest lake in the world?", choices: ["Lake Superior", "Lake Titicaca", "Lake Baikal", "Caspian Sea"], answer: 2 },
      { question: "The Strait of Malacca separates which two landmasses?", choices: ["Japan and Korea", "Malay Peninsula and Sumatra", "India and Sri Lanka", "Borneo and Java"], answer: 1 },
      { question: "What is the least densely populated country in the world?", choices: ["Iceland", "Australia", "Mongolia", "Namibia"], answer: 2 }
    ]
  },
  "technology": {
    easy: [
      { question: "What does CPU stand for?", choices: ["Central Processing Unit", "Computer Power Unit", "Core Processing Utility", "Central Program Unit"], answer: 0 },
      { question: "What company created the iPhone?", choices: ["Google", "Samsung", "Microsoft", "Apple"], answer: 3 },
      { question: "What does 'www' stand for in a web address?", choices: ["World Wide Web", "Wide World Web", "Web World Wide", "World Web Wide"], answer: 0 },
      { question: "What programming language is primarily used for web styling?", choices: ["JavaScript", "Python", "CSS", "HTML"], answer: 2 },
      { question: "What does RAM stand for?", choices: ["Random Access Memory", "Read Access Module", "Rapid Action Memory", "Remote Access Manager"], answer: 0 }
    ],
    medium: [
      { question: "What does HTTP stand for?", choices: ["HyperText Transfer Protocol", "High Text Transfer Process", "HyperText Transmission Program", "Hybrid Transfer Text Protocol"], answer: 0 },
      { question: "Which company developed the Android operating system?", choices: ["Apple", "Microsoft", "Samsung", "Google"], answer: 3 },
      { question: "What is the binary representation of the number 10?", choices: ["1001", "1100", "1010", "0110"], answer: 2 },
      { question: "What does SQL stand for?", choices: ["Standard Query Language", "Structured Query Language", "Simple Query Logic", "System Query Library"], answer: 1 },
      { question: "Which protocol assigns IP addresses automatically on a network?", choices: ["DNS", "FTP", "DHCP", "TCP"], answer: 2 }
    ],
    hard: [
      { question: "What is the time complexity of a binary search algorithm?", choices: ["O(n)", "O(n²)", "O(log n)", "O(1)"], answer: 2 },
      { question: "What does CORS stand for in web development?", choices: ["Cross-Origin Resource Sharing", "Client-Origin Request System", "Cross-Object Reference Standard", "Content Origin Routing Service"], answer: 0 },
      { question: "In machine learning, what is gradient descent used for?", choices: ["Data normalization", "Feature selection", "Minimizing a loss function", "Overfitting prevention"], answer: 2 },
      { question: "What cryptographic principle does a blockchain primarily rely on?", choices: ["Symmetric encryption", "Hashing and linked data structures", "Public key infrastructure", "Zero-knowledge proofs"], answer: 1 },
      { question: "What does the CAP theorem state about distributed systems?", choices: ["Speed, Accuracy, Precision cannot all be maximized", "Consistency, Availability, Partition tolerance — only 2 can be guaranteed", "Computing, Access, Performance are always trade-offs", "Cache, API, Protocol are interdependent"], answer: 1 }
    ]
  },
  "movies": {
    easy: [
      { question: "Which studio created the Toy Story franchise?", choices: ["DreamWorks", "Disney", "Pixar", "Universal"], answer: 2 },
      { question: "Who plays Iron Man in the MCU?", choices: ["Chris Evans", "Chris Hemsworth", "Robert Downey Jr.", "Mark Ruffalo"], answer: 2 },
      { question: "What 1994 film features a man waiting at a bus stop and saying 'Life is like a box of chocolates'?", choices: ["Cast Away", "Big", "Philadelphia", "Forrest Gump"], answer: 3 },
      { question: "What is the name of the lion in The Lion King?", choices: ["Mufasa", "Scar", "Simba", "Nala"], answer: 2 },
      { question: "Which film features the quote 'Here's looking at you, kid'?", choices: ["Casablanca", "Gone with the Wind", "Citizen Kane", "The Maltese Falcon"], answer: 0 }
    ],
    medium: [
      { question: "Who directed the movie Inception?", choices: ["Steven Spielberg", "James Cameron", "Christopher Nolan", "Denis Villeneuve"], answer: 2 },
      { question: "What year was the original Star Wars released?", choices: ["1975", "1977", "1979", "1980"], answer: 1 },
      { question: "Which actor played The Joker in The Dark Knight?", choices: ["Joaquin Phoenix", "Jack Nicholson", "Jared Leto", "Heath Ledger"], answer: 3 },
      { question: "What film won the first Academy Award for Best Picture?", choices: ["All Quiet on the Western Front", "Wings", "Sunrise", "The Jazz Singer"], answer: 1 },
      { question: "Which Kubrick film features the Overlook Hotel?", choices: ["A Clockwork Orange", "Full Metal Jacket", "The Shining", "Eyes Wide Shut"], answer: 2 }
    ],
    hard: [
      { question: "What film by Akira Kurosawa inspired The Magnificent Seven?", choices: ["Rashomon", "Yojimbo", "Seven Samurai", "Ran"], answer: 2 },
      { question: "Who composed the score for 2001: A Space Odyssey?", choices: ["John Williams", "It used pre-existing classical music", "Hans Zimmer", "Ennio Morricone"], answer: 1 },
      { question: "What is the Palme d'Or awarded at?", choices: ["Venice Film Festival", "Berlin International Film Festival", "Sundance", "Cannes Film Festival"], answer: 3 },
      { question: "Which film introduced the Steadicam technique in a memorable chase scene?", choices: ["The French Connection", "Bullitt", "Rocky", "Apocalypse Now"], answer: 2 },
      { question: "What film genre is defined by Nouvelle Vague?", choices: ["Italian Neorealism", "German Expressionism", "French New Wave Cinema", "Soviet Montage"], answer: 2 }
    ]
  }
};

// ============================================================
//  GENERATE QUIZ — picks from the question bank
// ============================================================
function generateQuiz() {
  const topic      = document.getElementById("topic").value.trim().toLowerCase();
  const difficulty = document.getElementById("difficulty").value;
  const num        = parseInt(document.getElementById("numQuestions").value);

  if (!topic) {
    alert("Please enter a topic first!");
    return;
  }

  // UI: loading state
  const btn     = document.getElementById("generateBtn");
  const btnText = document.getElementById("btnText");
  btn.disabled  = true;
  btnText.innerHTML = '<span class="spinner"></span> Generating…';

  document.getElementById("quizArea").style.display    = "none";
  document.getElementById("resultsArea").style.display = "none";

  setTimeout(() => {
    try {
      // Find best matching topic key
      const matchedKey = findBestMatch(topic);

      if (!matchedKey) {
        alert(`❌ No quiz available for "${topic}".\n\nAvailable topics: ${Object.keys(QUESTION_BANK).join(", ")}`);
        return;
      }

      const pool = QUESTION_BANK[matchedKey][difficulty] || QUESTION_BANK[matchedKey]["medium"];
      const shuffled = shuffle([...pool]);
      currentQuiz = shuffled.slice(0, Math.min(num, shuffled.length));
      userAnswers = {};

      if (currentQuiz.length === 0) {
        alert("Not enough questions for that combination. Try a different topic or difficulty.");
        return;
      }

      renderQuiz(matchedKey.charAt(0).toUpperCase() + matchedKey.slice(1));

    } catch (err) {
      console.error("Quiz generation failed:", err);
      alert("❌ Failed to generate quiz:\n" + err.message);
    } finally {
      btn.disabled  = false;
      btnText.innerHTML = "✨ Generate Quiz";
    }
  }, 600); // Slight delay for UX feel
}

// ============================================================
//  FUZZY TOPIC MATCHING
// ============================================================
function findBestMatch(input) {
  const keys = Object.keys(QUESTION_BANK);
  // Exact match
  if (keys.includes(input)) return input;
  // Partial match
  const partial = keys.find(k => input.includes(k) || k.includes(input));
  if (partial) return partial;
  // Synonym map
  const synonyms = {
    "tech": "technology", "computers": "technology", "coding": "technology", "programming": "technology",
    "film": "movies", "cinema": "movies", "films": "movies",
    "world history": "history", "us history": "history",
    "earth": "geography", "world": "geography", "countries": "geography",
    "biology": "science", "physics": "science", "chemistry": "science", "space": "science"
  };
  return synonyms[input] || null;
}

// ============================================================
//  SHUFFLE ARRAY (Fisher-Yates)
// ============================================================
function shuffle(arr) {
  for (let i = arr.length - 1; i > 0; i--) {
    const j = Math.floor(Math.random() * (i + 1));
    [arr[i], arr[j]] = [arr[j], arr[i]];
  }
  return arr;
}

// ============================================================
//  RENDER QUIZ
// ============================================================
function renderQuiz(topic) {
  document.getElementById("quizTopicLabel").textContent = topic;
  document.getElementById("progressText").textContent =
    `0 of ${currentQuiz.length} answered`;
  document.getElementById("progressBar").style.width = "0%";

  const container = document.getElementById("questionsContainer");
  container.innerHTML = "";

  currentQuiz.forEach((q, qi) => {
    const card = document.createElement("div");
    card.className = "question-card";
    card.id = `qcard-${qi}`;

    card.innerHTML = `
      <div class="question-num">Question ${qi + 1} of ${currentQuiz.length}</div>
      <div class="question-text">${escapeHtml(q.question)}</div>
      <div class="choices" id="choices-${qi}"></div>
    `;

    const choicesDiv = card.querySelector(`#choices-${qi}`);
    q.choices.forEach((choice, ci) => {
      const btn = document.createElement("button");
      btn.className = "choice-btn";
      btn.textContent = choice;
      btn.onclick = () => selectChoice(qi, ci);
      choicesDiv.appendChild(btn);
    });

    container.appendChild(card);
  });

  document.getElementById("submitBtn").style.display = "none";
  document.getElementById("quizArea").style.display  = "block";
  document.getElementById("quizArea").scrollIntoView({ behavior: "smooth" });
}

// ============================================================
//  SELECT A CHOICE
// ============================================================
function selectChoice(questionIndex, choiceIndex) {
  userAnswers[questionIndex] = choiceIndex;

  const choicesBtns = document.querySelectorAll(`#choices-${questionIndex} .choice-btn`);
  choicesBtns.forEach((btn, i) => {
    btn.classList.toggle("selected", i === choiceIndex);
  });

  const answered = Object.keys(userAnswers).length;
  const total    = currentQuiz.length;
  document.getElementById("progressText").textContent =
    `${answered} of ${total} answered`;
  document.getElementById("progressBar").style.width =
    `${Math.round((answered / total) * 100)}%`;

  if (answered === total) {
    document.getElementById("submitBtn").style.display = "block";
    document.getElementById("submitBtn").scrollIntoView({ behavior: "smooth" });
  }
}

// ============================================================
//  SUBMIT QUIZ & SHOW RESULTS
// ============================================================
function submitQuiz() {
  const total = currentQuiz.length;
  let correct = 0;

  const reviewContainer = document.getElementById("answersReview");
  reviewContainer.innerHTML = "<h3 style='margin-bottom:1rem;'>Answer Review</h3>";

  currentQuiz.forEach((q, qi) => {
    const userAnswer    = userAnswers[qi];
    const correctAnswer = q.answer;
    const isCorrect     = userAnswer === correctAnswer;

    if (isCorrect) correct++;

    const reviewCard = document.createElement("div");
    reviewCard.className = `review-card ${isCorrect ? "correct" : "incorrect"}`;

    const userAnswerText    = q.choices[userAnswer]    ?? "Not answered";
    const correctAnswerText = q.choices[correctAnswer] ?? "N/A";

    reviewCard.innerHTML = `
      <div class="review-q">${qi + 1}. ${escapeHtml(q.question)}</div>
      <div class="review-answer ${isCorrect ? "correct" : "incorrect"}">
        ${isCorrect ? "✅" : "❌"} Your answer: ${escapeHtml(userAnswerText)}
      </div>
      ${!isCorrect ? `<div class="review-correct-answer">✔ Correct: ${escapeHtml(correctAnswerText)}</div>` : ""}
    `;
    reviewContainer.appendChild(reviewCard);
  });

  const pct = Math.round((correct / total) * 100);
  document.getElementById("scorePercent").textContent = `${pct}%`;
  document.getElementById("scoreLabel").textContent   = "Score";
  document.getElementById("scoreDetail").textContent  = `You got ${correct} out of ${total} correct.`;

  let feedback;
  if (pct === 100)      feedback = "🏆 Perfect score! Outstanding!";
  else if (pct >= 80)   feedback = "🎉 Great job! You know your stuff!";
  else if (pct >= 60)   feedback = "👍 Good effort — keep studying!";
  else if (pct >= 40)   feedback = "📚 Not bad, but there's room to improve.";
  else                  feedback = "💪 Keep practicing — you'll get there!";

  document.getElementById("scoreFeedback").textContent = feedback;

  document.getElementById("quizArea").style.display    = "none";
  document.getElementById("resultsArea").style.display = "block";
  document.getElementById("resultsArea").scrollIntoView({ behavior: "smooth" });
}

// ============================================================
//  RESET
// ============================================================
function resetQuiz() {
  currentQuiz = [];
  userAnswers = {};
  document.getElementById("questionsContainer").innerHTML = "";
  document.getElementById("answersReview").innerHTML      = "";
  document.getElementById("resultsArea").style.display   = "none";
  document.getElementById("quizArea").style.display      = "none";
  document.getElementById("topic").value                  = "";
  document.getElementById("generate").scrollIntoView({ behavior: "smooth" });
}

// ============================================================
//  UTILITY
// ============================================================
function escapeHtml(str) {
  return String(str)
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;");
}

document.addEventListener("DOMContentLoaded", () => {
  document.getElementById("topic").addEventListener("keydown", (e) => {
    if (e.key === "Enter") generateQuiz();
  });
});
